### ISSUE TITLE
AttributeError: module 'CDPL' has no attribute 'ConfGen'

### ISSUE THREAD

**Issue by mainguyenanhvu** [molinfo-vienna/CDPKit#20]
# Context
I tried to modify [this code](https://github.com/ersilia-os/smiles-to-3d/blob/main/smiles3d/tools/gen_3d_structs.py) to convert SMILES to 3D SDF file.

## Installation
I activated my conda enviroment and install it.
```
pip install cdpkit
Collecting cdpkit
  Downloading CDPKit-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Downloading CDPKit-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 MB 611.3 kB/s eta 0:00:00
Installing collected packages: cdpkit
Successfully installed cdpkit-1.1.1
```

## My code
```
    status_to_str = { CDPL.ConfGen.ReturnCode.UNINITIALIZED                  : 'uninitialized',
                      CDPL.ConfGen.ReturnCode.TIMEOUT                        : 'max. processing time exceeded',
                      CDPL.ConfGen.ReturnCode.ABORTED                        : 'aborted',
                      CDPL.ConfGen.ReturnCode.FORCEFIELD_SETUP_FAILED        : 'force field setup failed',
                      CDPL.ConfGen.ReturnCode.FORCEFIELD_MINIMIZATION_FAILED : 'force field structure refinement failed',
                      CDPL.ConfGen.ReturnCode.FRAGMENT_LIBRARY_NOT_SET       : 'fragment library not available',
                      CDPL.ConfGen.ReturnCode.FRAGMENT_CONF_GEN_FAILED       : 'fragment conformer generation failed',
                      CDPL.ConfGen.ReturnCode.FRAGMENT_CONF_GEN_TIMEOUT      : 'fragment conformer generation timeout',
                      CDPL.ConfGen.ReturnCode.FRAGMENT_ALREADY_PROCESSED     : 'fragment already processed',
                      CDPL.ConfGen.ReturnCode.TORSION_DRIVING_FAILED         : 'torsion driving failed',
                      CDPL.ConfGen.ReturnCode.CONF_GEN_FAILED                : 'conformer generation failed' }
```

# Problem
```
status_to_str = { CDPL.ConfGen.ReturnCode.UNINITIALIZED                  : 'uninitialized',
AttributeError: module 'CDPL' has no attribute 'ConfGen'
```

Please help me to solve it. Thank you very much.

**Comment by mainguyenanhvu** [comment]
Moreover, I create a brand-new conda environment with `python=3.11` and install it:
```
pip install cdpkit
```

When I from CDPL import Pharm after installing `pip install numpy==2.0.0`, it said:
```
>>> from CDPL import Pharm

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/vumna/anaconda3/envs/CDPKit/lib/python3.11/site-packages/CDPL/Pharm/__init__.py", line 27, in <module>
    import CDPL.Biomol
  File "/home/vumna/anaconda3/envs/CDPKit/lib/python3.11/site-packages/CDPL/Biomol/__init__.py", line 27, in <module>
    import CDPL.Chem
  File "/home/vumna/anaconda3/envs/CDPKit/lib/python3.11/site-packages/CDPL/Chem/__init__.py", line 28, in <module>
    import CDPL.Math
  File "/home/vumna/anaconda3/envs/CDPKit/lib/python3.11/site-packages/CDPL/Math/__init__.py", line 29, in <module>
    from ._math import *
Traceback (most recent call last):
  File "/home/vumna/anaconda3/envs/CDPKit/lib/python3.11/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

**Comment by mainguyenanhvu** [comment]
I found that I have to:
```
import CDPL.ConfGen
```
