### ISSUE TITLE
Missing default value for an argument n in gen_confs.py

### ISSUE THREAD

**Issue by DrrDom** [molinfo-vienna/CDPKit#7]
A minor issue. It was mentioned in the help message that the default value of the argument `n` is 100. however, it was not set in the script and causes an error if a user does not supply it.

```
python gen_confs.py -i 1.sdf -o 1_conf.sdf 
Traceback (most recent call last):
  File "/home/pavel/tmp/conforge/gen_confs.py", line 180, in <module>
    main()
  File "/home/pavel/tmp/conforge/gen_confs.py", line 64, in main
    conf_gen.settings.maxNumOutputConformers = args.max_confs # apply the -n argument
Boost.Python.ArgumentError: Python argument types in
    None.None(ConformerGeneratorSettings, NoneType)
did not match C++ signature:
    None(CDPL::ConfGen::ConformerGeneratorSettings {lvalue}, unsigned long)
```

```
python gen_confs.py -i 1.sdf -o 1_conf.sdf -n 100
- Generating conformers for molecule 'n1' (#1)...
 -> Generated 12 conformer(s)
```

**Comment by seidelt** [comment]
Thank for reporting, has been fixed!
